---
title: async..await的错误处理方式
sidebar: auto
date: 2021-09-26 00:00:00
tags:
  - JavaScript
categories:
  - JavaScript
---

一般来说都是用 try..catch 来处理的

```
async function fn() {
  try {
    let res = await doSomething();
  } catch (err) {
    console.log(err)
  }
}
```

也可以直接 catch

```
async function fn() {

  let res = await doSomething().catch(e => e);

}
```
